spring:
  application:
    name: backend
  data:
    mongodb:
      uri: <YOUR_MONGODB_CONNECTION_STRING_URI>
      auto-index-creation: true # to enable auto index creation that allows to index email field as unique